### ISSUE TITLE
Data Graphs + Sample

### ISSUE THREAD

**Issue by lakshusan** [iKAN2025/frontend#3]
Make a code for graph after data input, create a sample set of data reflected on graph.

**Comment by eunseolim123** [comment]
- Created **instrument_chart.html** with sample data for one week (10-07 to 10-13)
        - X-axis are the dates, y-axis is the total practice time (minutes) per day
        - Border color and background colors customized
- Imported **Chart.js** for line graph in html file
- Linked graph to the **2023-10-12-passionproject-graphs.ipynb** with <iframe> (inline frame) element, embedding **instrument_chart.html** into the ipynb
- Commits "graphs" and "instrument tracker graphs" are related to this issue
