### ISSUE TITLE
Graphs

### ISSUE THREAD

**Issue by iKAN2025** [iKAN2025/frontend#7]
Connect user data to graphs

**Comment by eunseolim123** [comment]
- Created html files for each person w/ instrument (**eun's_graph.html, bella's_graph.html, lakshanya's_graph.html, avanthika's_graph.html**)
- Keys for the graphs include instrument name for each individual
- Imported **Chart.js** for all 4 line graphs
- Put all 4 html files under **passionproject** folder in VSCode frontend repository
- Used <iframe> (inline frame) element to embed graphs into the **graphs.md** markdown file
- Made sample data for all 4 graphs and customized colors to differentiate

**Key commits:**
- "graphs updated"
- "x-axis and y-axis updated"
- "x and y axis updated"
